const bookDummy = [
  {
    id: 1,
    title: 'Database System Concepts',
    author: 'Avi Silberschatz',
    isbn: '9780078022159',
    year: 2009,
    isComplete: true,
  },
  {
    id: 2,
    title: 'Book Writing for Popularity and Personal Branding',
    author: 'Haryono',
    isbn: '9786020447964',
    year: 2017,
    isComplete: true,
  },
  {
    id: 3,
    title:
      'Sirkuler informasi teknologi tanaman rempah dan obat : budidaya artemisia (Artemisa Annua)',
    author: 'Gusmaini',
    isbn: '9789795480655',
    year: 2017,
    isComplete: true,
  },
  {
    id: 4,
    title: 'The Pragmatic Programmer: Your Journey to Mastery',
    author: 'Andrew Hunt',
    isbn: '',
    year: 1999,
    isComplete: true,
  },
  {
    id: 5,
    title: 'Structure and Interpretation of Computer Programs',
    author: 'Harold Abelson',
    isbn: '',
    year: 1996,
    isComplete: true,
  },
  {
    id: 6,
    title: 'Clean Code: A Handbook of Agile Software Craftsmanship',
    author: 'Robert C. Martin',
    isbn: '',
    year: 2008,
    isComplete: false,
  },
  {
    id: 7,
    title: "Harry Potter and the Philosopher's Stone",
    author: 'JK Rowling',
    isbn: '',
    year: 1997,
    isComplete: false,
  },

  {
    id: 8,
    title: 'Harry Potter and the Chamber of Secrets',
    author: 'JK Rowling',
    isbn: '',
    year: 1998,
    isComplete: false,
  },
  {
    id: 9,
    title: 'Harry Potter and the Prisoner of Azkaban',
    author: 'JK Rowling',
    isbn: '',
    year: 1999,
    isComplete: false,
  },
  {
    id: 10,
    title: 'Harry Potter and the Goblet of Fire',
    author: 'JK Rowling',
    isbn: '',
    year: 2000,
    isComplete: false,
  },
  {
    id: 11,
    title: 'Harry Potter and the Order of the Phoenix',
    author: 'JK Rowling',
    isbn: '',
    year: 2003,
    isComplete: false,
  },
  {
    id: 12,
    title: 'Harry Potter and the Half-Blood Prince',
    author: 'JK Rowling',
    isbn: '',
    year: 2005,
    isComplete: false,
  },
  {
    id: 13,
    title: 'Harry Potter and the Deathly Hallows',
    author: 'JK Rowling',
    isbn: '',
    year: 2007,
    isComplete: false,
  },
  {
    id: 14,
    title: 'The Mysterious Affair at Styles',
    author: 'Agatha Christie',
    isbn: '',
    year: 1920,
    isComplete: false,
  },
  {
    id: 15,
    title: 'The Secret Adversary',
    author: 'Agatha Christie',
    isbn: '',
    year: 1922,
    isComplete: false,
  },
  {
    id: 16,
    title: 'The Murder on the Links',
    author: 'Agatha Christie',
    isbn: '',
    year: 1923,
    isComplete: true,
  },
  {
    id: 17,
    title: 'While the Light Lasts and Other Stories',
    author: 'Agatha Christie',
    isbn: '',
    year: 1997,
    isComplete: true,
  },
  {
    id: 18,
    title: 'The Big Four (short-story version)',
    author: 'Agatha Christie',
    isbn: '',
    year: 2017,
    isComplete: true,
  },
  {
    id: 19,
    title: 'Laskar Pelangi',
    author: 'Andrea Hirata',
    isbn: '',
    year: 2005,
    isComplete: true,
  },
  {
    id: 20,
    title: 'Sang Pemimpi',
    author: 'Andrea Hirata',
    isbn: '',
    year: 2006,
    isComplete: true,
  },
  {
    id: 21,
    title: 'Padang Bulan & Cinta di Dalam Gelas',
    author: 'Andrea Hirata',
    isbn: '',
    year: 2010,
    isComplete: true,
  },
  {
    id: 22,
    title: 'Orang-Orang Biasa',
    author: 'Andrea Hirata',
    isbn: '',
    year: 2019,
    isComplete: true,
  },
  {
    id: 23,
    title: 'Bumi Manusia',
    author: 'Pramoedya Ananta Toer',
    isbn: '',
    year: 1980,
    isComplete: true,
  },
  {
    id: 24,
    title: 'Rumah Kaca',
    author: 'Pramoedya Ananta Toer',
    isbn: '',
    year: 1988,
    isComplete: true,
  },
  {
    id: 25,
    title: 'Hujan Bulan Juni',
    author: 'Sapardi Djoko Damono',
    isbn: '',
    year: 1991,
    isComplete: true,
  },
  {
    id: 26,
    title: 'Pada Suatu Hari Nanti',
    author: 'Sapardi Djoko Damono',
    isbn: '',
    year: 2013,
    isComplete: false,
  },
  {
    id: 27,
    title: 'Dilan : Dia Adalah Dilanku Tahun 1990',
    author: 'Pidi Baiq',
    isbn: '',
    year: 2014,
    isComplete: true,
  },
  {
    id: 28,
    title: 'Dilan Bagian Kedua : Dia Adalah Dilanku Tahun 1991',
    author: 'Pidi Baiq',
    isbn: '',
    year: 2015,
    isComplete: true,
  },
  {
    id: 29,
    title: 'Millea : Voice From Dilan',
    author: 'Pidi Baiq',
    isbn: '',
    year: 2016,
    isComplete: true,
  },
  {
    id: 30,
    title: 'Catatan Seorang Demonstran',
    author: 'Soe Hok Gie',
    isbn: '',
    year: 1983,
    isComplete: true,
  },
  {
    id: 31,
    title: 'The Communist Manifesto',
    author: 'Karl Marx',
    isbn: '',
    year: 1848,
    isComplete: true,
  },
  {
    id: 32,
    title: 'Rembulan Tenggelam di Wajahmu',
    author: 'Tere Liye',
    isbn: '',
    year: 2009,
    isComplete: true,
  },
  {
    id: 33,
    title: 'Sunset Bersama Rosie',
    author: 'Tere Liye',
    isbn: '',
    year: 2008,
    isComplete: true,
  },
  {
    id: 34,
    title: 'Yang Fana Adalah Waktu',
    author: 'Sapardi Djoko Damono',
    isbn: '',
    year: 2017,
    isComplete: false,
  },
  {
    id: 35,
    title: 'Sepotong Senja Untuk Pacarku',
    author: 'Seno Gumira Ajidarma',
    isbn: '',
    year: 2002,
    isComplete: false,
  },
  {
    id: 36,
    title:
      'Basics of Reservoir Simulation with the Eclipse Reservoir Simulator',
    author: 'Oystein Pettersen',
    isbn: '',
    year: 2006,
    isComplete: false,
  },
  {
    id: 37,
    title: 'Seluk Beluk Database Relasional (Edisi Kedua)',
    author: 'Mark Whitehorn',
    isbn: '',
    year: 2003,
    isComplete: false,
  },
  {
    id: 38,
    title: 'Algoritma & Teknik Pemrograman',
    author: 'Budi Sutejo',
    isbn: '',
    year: 2000,
    isComplete: false,
  },
  {
    id: 39,
    title: 'Computers and Programming',
    author: 'Francis Scheid',
    isbn: '',
    year: 1983,
    isComplete: true,
  },
  {
    id: 40,
    title: 'The Intelligent Investor',
    author: 'Benjamin Graham',
    isbn: '',
    year: 1949,
    isComplete: true,
  },
  {
    id: 41,
    title: 'Smart Trader Rich Investor',
    author: 'Ellen May',
    isbn: '',
    year: 2013,
    isComplete: true,
  },
];
